FORMAT: 1A
HOST: www.test.66rpg.com

# 架空

架空界面搜索API

## 获取查询结果 [/searchapi/index]

### 通用查询接口 [GET]

+ Response 200 (application/json)

        [
            {
                "total": 27,
                "result": [
                    {
                        "gname": "鲜果神",
                        "real_gname": "鲜果神",
                        "uname": "wanglijing",
                        "thumb": "http://pic.cgyouxi.com/orange/title/42a399c726073b16e1e8c3fa00c5deb2_3.jpg",
                        "flower": 11,
                        "star": 0,
                        "release_word_sum": 0,
                        "complete_flag": true,
                        "check_level": 2,
                        "tag": [
                            "新作",
                            "完结"
                        ]
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }